"use strict";
(()=>{
 const core=new Set(["courses","lessons","calendar","tasks","community","qa","meetings"]);
 const esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 const db=()=>window.AMPRO_AUTH?.client||null;
 const layouts={courses:["Courses","Your academic spaces","Browse enrolled courses, modules and learning material.","courses"],lessons:["Lessons","Continue learning","Open lessons, lecture material and course resources.","lessons"],calendar:["Calendar","Academic calendar","Keep classes, meetings, deadlines and events together.","calendar_events"],tasks:["Tasks & Goals","Plan your study","Track assignments, revision goals and personal study tasks.","tasks"],community:["Community","Academic community","Discuss learning with students, tutors and educators.","community_posts"],qa:["Q&A","Ask. Answer. Learn.","A focused space for academic questions and useful answers.","community_posts"],meetings:["Meetings","Live academic connections","Classes, tutorials and external Zoom, Meet or Teams sessions.","calendar_events"]};
 function card(route,title,subtitle){return `<section class="bridge-head glass"><p class="eyebrow">ACADEMIC BRIDGE</p><h2>${esc(title)}</h2><p>${esc(subtitle)}</p><div class="bridge-actions"><button class="primary" data-bridge-refresh="${route}">Refresh</button></div></section><section id="bridgeData" class="bridge-grid"><article class="glass bridge-empty"><b>Loading…</b><small>Connecting securely to your workspace.</small></article></section>`}
 function normalize(x){return x.title||x.name||x.question||x.content||x.event_title||"Untitled"}
 async function getClient(){for(let i=0;i<20;i++){if(db())return db();await new Promise(r=>setTimeout(r,100))}return null}
 async function load(route){const [,title,subtitle,table]=layouts[route];const app=document.getElementById("app");if(!app)return;app.innerHTML=card(route,title,subtitle);const target=document.getElementById("bridgeData");try{const client=await getClient();if(!client?.from)throw new Error("Secure database session is unavailable. Please refresh once.");let q=client.from(table).select("*").limit(24);const {data,error}=await q;if(error)throw error;if(!data?.length){target.innerHTML=`<article class="glass bridge-empty"><b>No ${esc(title.toLowerCase())} yet</b><small>The database is connected. This workspace is ready for its first record.</small></article>`;return}target.innerHTML=data.map(x=>`<article class="glass bridge-card"><small>${esc(route.toUpperCase())}</small><h3>${esc(normalize(x))}</h3><p>${esc(x.description||x.summary||x.content||x.body||x.location||"Open this workspace to continue.")}</p></article>`).join("")}catch(e){target.innerHTML=`<article class="glass bridge-empty"><b>Database response</b><small>${esc(e.message||"Unable to load records right now.")}</small></article>`}}
 function bind(){document.addEventListener("click",e=>{const b=e.target.closest("button[data-route]");if(!b||!core.has(b.dataset.route))return;e.preventDefault();e.stopImmediatePropagation();document.querySelectorAll(".nav button").forEach(x=>x.classList.toggle("active",x===b));load(b.dataset.route)},true);document.addEventListener("click",e=>{const b=e.target.closest("[data-bridge-refresh]");if(b)load(b.dataset.bridgeRefresh)})}
 document.readyState==="loading"?document.addEventListener("DOMContentLoaded",bind,{once:true}):bind();
})();