"use strict";
const cfg=window.AMPRO_CONFIG||{},ok=cfg.supabaseUrl&&!cfg.supabaseUrl.includes("YOUR_PROJECT");
const c=ok&&window.supabase?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true}}):null,$=x=>document.getElementById(x);
let heartbeat=null,refreshClock=null,secondsToRefresh=30,loading=false,sessionShowAll=false,lastSessionRows=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const ago=t=>{const s=Math.max(0,Math.floor((Date.now()-new Date(t).getTime())/1000));return s<60?s+"s ago":s<3600?Math.floor(s/60)+"m ago":s<86400?Math.floor(s/3600)+"h ago":Math.floor(s/86400)+"d ago"};
const dur=(a,b)=>{const sec=Math.max(0,Math.floor((new Date(b||Date.now())-new Date(a))/1000)),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return (h?h+"h ":"")+(m?m+"m ":"")+s+"s"};
const localDayStartISO=()=>{const d=new Date();d.setHours(0,0,0,0);return d.toISOString()};
function deny(msg){$("blocked")?.classList.add("show");const p=$("blocked")?.querySelector("p");if(p)p.textContent=msg;if($("console"))$("console").hidden=true}
function beginRefreshClock(){if(refreshClock)return;refreshClock=setInterval(async()=>{secondsToRefresh--;if($("autoRefresh"))$("autoRefresh").textContent="Auto refresh in "+Math.max(0,secondsToRefresh)+"s";if(secondsToRefresh<=0){secondsToRefresh=30;await load()}},1000)}
function setSecurityStatus(events){const recent=events.filter(e=>Date.now()-new Date(e.created_at).getTime()<300000),critical=recent.filter(e=>e.decision==="block"||Number(e.risk_score)>=75).length,suspicious=recent.filter(e=>e.decision==="verify"||(Number(e.risk_score)>=45&&Number(e.risk_score)<75)).length,failed=recent.filter(e=>e.event_type==="login_failed").length,el=$("securityStatus"),meta=$("securityStatusMeta");if(!el||!meta)return;if(critical){el.textContent="CRITICAL";el.className="danger";meta.textContent=critical+" blocked/high-risk event(s) in last 5 min"}else if(suspicious||failed>=3){el.textContent="ATTENTION";el.className="danger";meta.textContent=(suspicious+failed)+" suspicious/failed event(s) in last 5 min"}else{el.textContent="PROTECTED";el.className="green";meta.textContent="No high-risk signals observed in last 5 min"}}
async function profileMapFor(ids){const unique=[...new Set(ids.filter(Boolean))];if(!unique.length)return new Map();const {data,error}=await c.from("profiles").select("id,full_name,role,status").in("id",unique);if(error){console.warn("Profile lookup failed",error.message);return new Map()}return new Map((data||[]).map(p=>[p.id,p]))}
async function deleteSessions(ids,label){ids=[...new Set((ids||[]).filter(Boolean))];if(!ids.length)return;if(!confirm("Delete "+label+"? This cannot be undone."))return;try{const {error}=await c.rpc("admin_delete_session_records",{session_ids:ids});if(error)throw error;await load()}catch(e){alert("Delete failed: "+(e?.message||"Unknown error")+"\n\nIf this RPC has not been installed yet, run the admin archive delete migration once in Supabase.")}}
function renderSessions(sessions,profiles){lastSessionRows=sessions||[];const host=$("sessions");if(!host)return;const visible=sessionShowAll?lastSessionRows:lastSessionRows.slice(0,10);let html="";if(visible.length){html='<div class="row session-bulk"><label><input id="selectAllSessions" type="checkbox"> <strong>Select all</strong></label><span id="sessionSelectedCount">0 selected</span><button id="deleteSelectedSessions" class="session-delete" disabled>Delete selected</button><button id="deleteAllSessions" class="session-delete">Delete all</button></div>';html+=visible.map(s=>{const pr=profiles.get(s.user_id)||{},live=!s.ended_at&&Date.now()-new Date(s.last_seen_at).getTime()<180000,loc=[s.city,s.region,s.country_code].filter(Boolean).join(", ")||"Location unavailable",network=s.tor?"TOR":s.vpn?"VPN":"Direct/unknown",role=String(pr.role||"member").toUpperCase();return '<div class="row"><input class="session-check" type="checkbox" value="'+esc(s.id)+'" aria-label="Select session"><div><strong>'+esc(pr.full_name||"Member")+' • '+esc(role)+(live?' • LIVE':'')+'</strong><small>Login: '+new Date(s.started_at).toLocaleString()+' • Last activity: '+ago(s.last_seen_at)+' • Session duration: '+dur(s.started_at,s.ended_at||s.last_seen_at)+'</small><small>'+esc([s.device_label,s.browser_label,s.os_label].filter(Boolean).join(" • ")||"Device information unavailable")+' • '+esc(loc)+' • '+esc(network)+(s.ended_at?' • Logout: '+new Date(s.ended_at).toLocaleString():'')+'</small></div></div>'}).join("")}else html='<div class="row"><small>No session telemetry yet.</small></div>';host.innerHTML=html;if(lastSessionRows.length>10){host.insertAdjacentHTML("beforeend",'<div class="row session-more-row"><button id="toggleSessionHistory" class="secondary-btn">'+(sessionShowAll?'Show less':'Show all '+lastSessionRows.length+' sessions')+'</button></div>')}const checks=[...host.querySelectorAll(".session-check")],all=$("selectAllSessions"),count=$("sessionSelectedCount"),del=$("deleteSelectedSessions");const sync=()=>{const selected=checks.filter(x=>x.checked);if(count)count.textContent=selected.length+" selected";if(del)del.disabled=!selected.length;if(all){all.checked=checks.length>0&&selected.length===checks.length;all.indeterminate=selected.length>0&&selected.length<checks.length}};checks.forEach(x=>x.onchange=sync);if(all)all.onchange=()=>{checks.forEach(x=>x.checked=all.checked);sync()};if(del)del.onclick=()=>deleteSessions(checks.filter(x=>x.checked).map(x=>x.value),"selected session records");$("deleteAllSessions")?.addEventListener("click",()=>deleteSessions(lastSessionRows.map(x=>x.id),"ALL session records currently loaded"));$("toggleSessionHistory")?.addEventListener("click",()=>{sessionShowAll=!sessionShowAll;renderSessions(lastSessionRows,profiles)})}
async function load(){if(loading)return;loading=true;const refreshBtn=$("refresh");if(refreshBtn){refreshBtn.disabled=true;refreshBtn.textContent="Refreshing…"}try{
 if(!c)return deny("Backend configuration is not connected yet.");
 const {data:{session}}=await c.auth.getSession();if(!session)return deny("Sign in with an administrator account.");
 $("adminEmail").textContent=session.user.email||"Admin";
 const {data:p,error:pe}=await c.from("profiles").select("id,full_name,role,status").eq("id",session.user.id).maybeSingle();if(pe||p?.role!=="admin"||p?.status!=="active")return deny("Your account is not authorised for this console.");
 await window.AMPRO_SESSION_TRACKER?.ensure("admin");beginRefreshClock();$("blocked")?.classList.remove("show");if($("console"))$("console").hidden=false;
 const since24=new Date(Date.now()-86400000).toISOString(),today=localDayStartISO(),activeSince=new Date(Date.now()-180000).toISOString();
 const [aq,pp,ev,ss,todayRows,totalRes,visitsRes,activeRows]=await Promise.all([
  c.from("approval_requests").select("id,user_id,state,created_at").eq("state","pending").order("created_at"),
  c.from("profiles").select("id,full_name,status,created_at").eq("status","pending").order("created_at"),
  c.from("security_events").select("id,user_id,event_type,risk_score,decision,country_code,user_agent_summary,metadata,created_at").gte("created_at",since24).order("created_at",{ascending:false}).limit(200),
  c.from("session_activity").select("id,user_id,started_at,last_seen_at,ended_at,country_code,city,region,device_label,browser_label,os_label,vpn,tor,ip_hash").order("started_at",{ascending:false}).limit(100),
  c.from("session_activity").select("user_id").gte("started_at",today).limit(5000),
  c.from("session_activity").select("id",{count:"exact",head:true}),
  c.from("session_activity").select("id",{count:"exact",head:true}).gte("started_at",today),
  c.from("session_activity").select("user_id,last_seen_at").is("ended_at",null).gte("last_seen_at",activeSince).limit(5000)
 ]);
 const sessions=ss.error?[]:(ss.data||[]),events=ev.error?[]:(ev.data||[]),ids=[session.user.id,...sessions.map(x=>x.user_id),...events.map(x=>x.user_id),...(aq.data||[]).map(x=>x.user_id)];const profiles=await profileMapFor(ids);
 const byUser=new Map();(aq.data||[]).forEach(a=>{const pr=profiles.get(a.user_id);byUser.set(a.user_id,{user_id:a.user_id,created_at:a.created_at,full_name:pr?.full_name||"New member"})});(pp.data||[]).forEach(x=>{if(!byUser.has(x.id))byUser.set(x.id,{user_id:x.id,created_at:x.created_at,full_name:x.full_name||"New member"})});const approvals=[...byUser.values()].sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));
 const onlineUsers=new Set((activeRows.data||[]).map(x=>x.user_id)).size,uniqueToday=new Set((todayRows.data||[]).map(x=>x.user_id)).size;
 setSecurityStatus(events);$("pendingCount").textContent=approvals.length;$("activeCount").textContent=onlineUsers;$("visitsToday").textContent=visitsRes.count??0;$("uniqueToday").textContent=uniqueToday;$("totalSessions").textContent=totalRes.count??0;$("eventCount").textContent=events.length;$("riskCount").textContent=events.filter(e=>Number(e.risk_score)>=45).length;
 $("approvals").innerHTML=approvals.length?approvals.map(a=>'<div class="row"><div><strong>'+esc(a.full_name)+'</strong><small>'+esc(a.user_id)+' • '+new Date(a.created_at).toLocaleString()+'</small></div><button class="approve" data-user="'+esc(a.user_id)+'">Approve</button></div>').join(""):'<div class="row"><small>No pending approvals.</small></div>';
 renderSessions(sessions,profiles);
 $("lastRefresh").textContent="Last secure refresh: "+new Date().toLocaleTimeString();secondsToRefresh=30;if($("autoRefresh"))$("autoRefresh").textContent="Auto refresh in 30s";document.querySelectorAll(".approve").forEach(b=>b.onclick=()=>approve(b.dataset.user));
 }catch(e){console.error("Admin load failed",e);deny("Admin telemetry could not be loaded: "+(e?.message||"Unknown error"))}finally{loading=false;if(refreshBtn){refreshBtn.disabled=false;refreshBtn.textContent="Refresh now"}}}
async function approve(userId){if(!confirm("Approve this member as a student?"))return;try{const {error}=await c.rpc("approve_member",{target:userId,new_role:"student"});if(error)throw error;await load()}catch(e){alert(e.message||"Approval failed")}}
$("refresh").onclick=()=>{secondsToRefresh=30;load()};$("logout").onclick=async()=>{if(refreshClock)clearInterval(refreshClock);await window.AMPRO_SESSION_TRACKER?.end();if(c)await c.auth.signOut();location.href="auth.html"};load();
