"use strict";
const cfg=window.AMPRO_CONFIG||{},$=id=>document.getElementById(id);
const api=String(cfg.supabaseUrl||"").replace(/\/$/,""),key=cfg.supabaseAnonKey||"";
const forms={login:$("loginForm"),register:$("registerForm"),recovery:$("recoveryForm")};
const client=(window.supabase&&api&&key)?window.supabase.createClient(api,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,experimental:{passkey:true}}}):null;
function notice(m,t="info"){const e=$("notice");e.textContent=m;e.className="notice show "+t;e.scrollIntoView({behavior:"smooth",block:"nearest"})}
function clearNotice(){const e=$("notice");e.textContent="";e.className="notice"}
function show(mode){clearNotice();Object.values(forms).forEach(f=>f.classList.remove("active"));forms[mode].classList.add("active");document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.mode===mode))}
function busy(f,on){f.querySelectorAll("button,input").forEach(x=>x.disabled=on)}
async function request(path,options={}){const r=await fetch(api+path,{...options,headers:{apikey:key,"Content-Type":"application/json",...(options.headers||{})},cache:"no-store"});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||"Secure request failed");return d}
function storeSession(s){const ref=new URL(api).hostname.split(".")[0];localStorage.setItem("sb-"+ref+"-auth-token",JSON.stringify(s))}
async function routeApprovedSession(session){if(!session?.user)throw new Error("A secure session could not be created.");const p=await request("/rest/v1/profiles?id=eq."+encodeURIComponent(session.user.id)+"&select=status,role",{headers:{Authorization:"Bearer "+session.access_token}});const profile=Array.isArray(p)?p[0]:null;if(!profile)throw new Error("Your security profile was not found.");if(profile.status!=="active"){if(client)await client.auth.signOut();throw new Error("Your account is pending administrator approval.");}notice("Identity verified. Opening secure workspace…","success");setTimeout(()=>location.replace(profile.role==="admin"?"admin.html":(cfg.siteUrl||"index.html")),350)}
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>show(t.dataset.mode));
document.querySelectorAll(".reveal").forEach(b=>b.onclick=()=>{const i=$(b.dataset.target);i.type=i.type==="password"?"text":"password";b.textContent=i.type==="password"?"Show":"Hide"});
$("backHome").onclick=()=>location.href="index.html";$("showRecovery").onclick=()=>show("recovery");$("backLogin").onclick=()=>show("login");
$("registerPassword").oninput=e=>{const v=e.target.value;let s=0;s+=v.length>=12;s+=/[a-z]/.test(v)&&/[A-Z]/.test(v);s+=/\d/.test(v);s+=/[^A-Za-z0-9]/.test(v);$("strengthBar").style.width=[0,25,50,75,100][s]+"%";$("strengthBar").style.background=s<2?"#ff6b7a":s<4?"#ffc36f":"#63efc7";$("strengthText").textContent=["Start with at least 12 characters.","Weak — add length and variety.","Fair — add uppercase, number and symbol.","Good — one more improvement.","Strong password."][s]};
forms.login.onsubmit=async e=>{e.preventDefault();clearNotice();busy(e.currentTarget,true);try{if(!api||!key)throw new Error("Secure service configuration is unavailable.");const session=await request("/auth/v1/token?grant_type=password",{method:"POST",body:JSON.stringify({email:$("loginEmail").value.trim(),password:$("loginPassword").value})});storeSession(session);await routeApprovedSession(session)}catch(err){notice(err.message||"Sign-in failed.","error")}finally{busy(e.currentTarget,false)}};
forms.register.onsubmit=async e=>{e.preventDefault();busy(e.currentTarget,true);try{const password=$("registerPassword").value;if(password.length<12||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/[0-9]/.test(password)||!/[^A-Za-z0-9]/.test(password))throw new Error("Use 12+ characters, mixed case, a number and a symbol.");await request("/auth/v1/signup?redirect_to="+encodeURIComponent(cfg.authUrl||location.href),{method:"POST",body:JSON.stringify({email:$("registerEmail").value.trim(),password,data:{full_name:$("fullName").value.trim(),anti_phishing_phrase:$("phishingPhrase").value.trim()}})});notice("Check your email to verify the account. Administrator approval follows verification.","success");e.currentTarget.reset()}catch(err){notice(err.message||"Registration failed.","error")}finally{busy(e.currentTarget,false)}};
forms.recovery.onsubmit=async e=>{e.preventDefault();busy(e.currentTarget,true);try{if(client){const {error}=await client.auth.resetPasswordForEmail($("recoveryEmail").value.trim(),{redirectTo:(cfg.authUrl||location.href)+"?recovery=1"});if(error)throw error}else{await request("/auth/v1/recover?redirect_to="+encodeURIComponent((cfg.authUrl||location.href)+"?recovery=1"),{method:"POST",body:JSON.stringify({email:$("recoveryEmail").value.trim()})})}notice("If the address is registered, a secure recovery email has been sent.","success")}catch(err){notice(err.message||"Recovery failed.","error")}finally{busy(e.currentTarget,false)}};
const recoveryHash=new URLSearchParams(location.hash.replace(/^#/,""));
if(recoveryHash.get("type")==="recovery"&&recoveryHash.get("access_token")){
  show("recovery");
  forms.recovery.innerHTML='<header><p>SECURE RECOVERY</p><h2>Choose a new password</h2><span>Create a unique password you have never used before.</span></header><label>New password<div class="input-wrap"><input id="newRecoveryPassword" type="password" autocomplete="new-password" placeholder="At least 12 characters" minlength="12" required><button class="reveal" id="recoveryReveal" type="button">Show</button></div></label><button class="primary-btn" type="submit">Update password securely <span>→</span></button>';
  $("recoveryReveal").onclick=()=>{const i=$("newRecoveryPassword");i.type=i.type==="password"?"text":"password";$("recoveryReveal").textContent=i.type==="password"?"Show":"Hide"};
  forms.recovery.onsubmit=async e=>{e.preventDefault();busy(e.currentTarget,true);try{const password=$("newRecoveryPassword").value;if(password.length<12||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/[0-9]/.test(password)||!/[^A-Za-z0-9]/.test(password))throw new Error("Use 12+ characters, mixed case, a number and a symbol.");await request("/auth/v1/user",{method:"PUT",headers:{Authorization:"Bearer "+recoveryHash.get("access_token")},body:JSON.stringify({password})});location.hash="";notice("Password updated. Return to Sign in and use your new password.","success");setTimeout(()=>show("login"),1200)}catch(err){notice(err.message||"Password update failed.","error")}finally{busy(e.currentTarget,false)}};
}
$("googleLogin").onclick=async()=>{try{if(!client)throw new Error("Secure service configuration is unavailable.");$("googleLogin").disabled=true;const {error}=await client.auth.signInWithOAuth({provider:"google",options:{redirectTo:cfg.siteUrl||location.origin+location.pathname.replace(/auth\.html$/,"index.html")}});if(error)throw error}catch(err){$("googleLogin").disabled=false;notice(err.message||"Google sign-in failed.","error")}};
$("passkeyLogin").onclick=async()=>{try{if(!client)throw new Error("Secure service configuration is unavailable.");if(!window.PublicKeyCredential)throw new Error("This browser or device does not support passkeys.");$("passkeyLogin").disabled=true;notice("Use Face ID, Touch ID, device PIN or your security key to continue…","info");const {data,error}=await client.auth.signInWithPasskey();if(error)throw error;await routeApprovedSession(data?.session)}catch(err){$("passkeyLogin").disabled=false;notice(err.message||"Passkey sign-in failed.","error")}};
const qs=new URLSearchParams(location.search);if(qs.get("status")==="pending")notice("Your account is verified but still waiting for administrator approval.","info");if(qs.get("error")==="auth")notice("Authentication could not be completed. Please sign in again.","error");
