"use strict";
const cfg=window.AMPRO_CONFIG||{};
const configured=cfg.supabaseUrl&&!cfg.supabaseUrl.includes("YOUR_PROJECT")&&cfg.supabaseAnonKey&&!cfg.supabaseAnonKey.includes("YOUR_");
const client=configured&&window.supabase?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
const $=id=>document.getElementById(id);
const forms={login:$("loginForm"),register:$("registerForm"),recovery:$("recoveryForm")};
function notice(message,type="info"){const el=$("notice");el.textContent=message;el.className="notice show "+type;}
function clearNotice(){const el=$("notice");el.textContent="";el.className="notice";}
function show(mode){clearNotice();Object.values(forms).forEach(f=>f.classList.remove("active"));forms[mode].classList.add("active");document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.mode===mode));}
function ready(){if(!client){notice("Secure interface is ready. Connect the Supabase project in config.js to activate real sign-in, verification and recovery.","info");return false}return true}
function busy(form,on){form.querySelectorAll("button,input").forEach(x=>x.disabled=on)}
document.querySelectorAll(".tab").forEach(t=>t.addEventListener("click",()=>show(t.dataset.mode)));
document.querySelectorAll(".reveal").forEach(b=>b.addEventListener("click",()=>{const i=$(b.dataset.target);i.type=i.type==="password"?"text":"password";b.textContent=i.type==="password"?"Show":"Hide"}));
$("backHome").onclick=()=>location.href="index.html";$("showRecovery").onclick=()=>show("recovery");$("backLogin").onclick=()=>show("login");
$("registerPassword").addEventListener("input",e=>{const v=e.target.value;let s=0;s+=v.length>=12;s+=/[a-z]/.test(v)&&/[A-Z]/.test(v);s+=/\d/.test(v);s+=/[^A-Za-z0-9]/.test(v);const w=[0,25,50,75,100][s];$("strengthBar").style.width=w+"%";$("strengthBar").style.background=s<2?"#ff6b7a":s<4?"#ffc36f":"#63efc7";$("strengthText").textContent=["Start with at least 12 characters.","Weak — add length and variety.","Fair — add uppercase, number and symbol.","Good — one more improvement.","Strong password."][s]});
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();if(!ready())return;busy(e.currentTarget,true);try{const {data,error}=await client.auth.signInWithPassword({email:$("loginEmail").value.trim(),password:$("loginPassword").value});if(error)throw error;const {data:profile}=await client.from("profiles").select("status,role").eq("id",data.user.id).single();if(profile?.status==="suspended")throw new Error("This account is suspended. Contact an administrator.");if(profile?.status==="pending"){await client.auth.signOut();notice("Email verified. Your membership is pending administrator approval.","info");return}location.href=cfg.redirectUrl||"index.html"}catch(err){notice(err.message||"Sign-in failed. Please verify your details.","error")}finally{busy(e.currentTarget,false)}});
$("registerForm").addEventListener("submit",async e=>{e.preventDefault();if(!ready())return;busy(e.currentTarget,true);try{const password=$("registerPassword").value;if(password.length<12||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/[0-9]/.test(password)||!/[^A-Za-z0-9]/.test(password))throw new Error("Choose a stronger password with 12+ characters, mixed case, a number and a symbol.");const {error}=await client.auth.signUp({email:$("registerEmail").value.trim(),password,options:{emailRedirectTo:cfg.redirectUrl,data:{full_name:$("fullName").value.trim(),anti_phishing_phrase:$("phishingPhrase").value.trim()}}});if(error)throw error;notice("Check your email for the verification link. After verification, an administrator must approve your access.","success");e.currentTarget.reset()}catch(err){notice(err.message||"Registration failed.","error")}finally{busy(e.currentTarget,false)}});
$("recoveryForm").addEventListener("submit",async e=>{e.preventDefault();if(!ready())return;busy(e.currentTarget,true);try{const {error}=await client.auth.resetPasswordForEmail($("recoveryEmail").value.trim(),{redirectTo:location.origin+location.pathname+"?recovery=1"});if(error)throw error;notice("If that address is registered, a short-lived reset link has been sent.","success")}catch(err){notice(err.message||"Recovery request failed.","error")}finally{busy(e.currentTarget,false)}});
$("googleLogin").onclick=async()=>{if(!ready())return;const {error}=await client.auth.signInWithOAuth({provider:"google",options:{redirectTo:cfg.redirectUrl}});if(error)notice(error.message,"error")};
$("passkeyLogin").onclick=()=>notice("Passkeys require a verified WebAuthn server endpoint. The interface is ready; server-side enrolment must be enabled before activation.","info");
(async()=>{if(!client)return;const {data}=await client.auth.getSession();if(data.session){const {data:p}=await client.from("profiles").select("status").eq("id",data.session.user.id).single();if(p?.status==="active")location.href=cfg.redirectUrl||"index.html"}})();
