(()=>{const A=(topic,q,a,d,e,tags='',visual='')=>window.QUIZ_DATA.push({topic,q,a,d,e,tags,visual});const T=[
['Blood basics','6.0','Haematology','the study of blood'],['Blood basics','6.0','Blood volume in an average adult','about 5 litres'],['Blood basics','6.0','Blood as a percentage of body weight','about 8%'],['Blood basics','6.0','Normal blood pH','7.35–7.45'],['Blood basics','6.0','Whole-blood viscosity','about 5 times thicker than water'],['Blood basics','6.0','Oxygen-rich blood colour','scarlet red'],['Blood basics','6.0','Oxygen-poor blood colour','dull red'],['Blood basics','6.0','Blood tissue classification','liquid connective tissue'],['Blood basics','6.0','Main functions of blood','transport, regulation and protection'],['Blood basics','6.0','Blood location','inside the heart and blood vessels'],
['Blood composition','6.0','Plasma','the transparent straw-coloured liquid part of blood'],['Blood composition','6.0','Formed elements','red blood cells, white blood cells and platelets'],['Blood composition','6.0','Approximate plasma proportion','55% of whole blood'],['Blood composition','6.0','Approximate RBC proportion','45% of whole blood'],['Blood composition','6.0','Buffy coat proportion','less than 1% of whole blood'],['Blood composition','6.0','Top layer after centrifugation','plasma'],['Blood composition','6.0','Middle layer after centrifugation','buffy coat: white blood cells and platelets'],['Blood composition','6.0','Bottom layer after centrifugation','red blood cells'],['Blood composition','6.0','Main component of plasma','water, about 91%'],['Blood composition','6.0','Plasma proteins','about 8% of plasma'],['Blood composition','6.0','Other dissolved solutes','about 1% of plasma'],['Blood composition','6.0','Albumin','a major plasma protein'],['Blood composition','6.0','Immunoglobulins','antibodies found among plasma proteins'],['Blood composition','6.0','Fibrinogen','a dissolved clotting protein that forms fibrin strands'],['Blood composition','6.0','Examples of plasma electrolytes','sodium, potassium, chloride and calcium ions'],['Blood composition','6.0','Examples of plasma nutrients','glucose, fatty acids and amino acids'],['Blood composition','6.0','Example of a plasma waste product','urea'],
['RBC & haemoglobin','6.1','Erythrocyte','the scientific name for a red blood cell'],['RBC & haemoglobin','6.1','Mature erythrocyte shape','small biconcave disc'],['RBC & haemoglobin','6.1','Mature erythrocyte nucleus','absent'],['RBC & haemoglobin','6.1','Advantage of losing the RBC nucleus','more internal space for haemoglobin'],['RBC & haemoglobin','6.1','Advantage of biconcave shape','large exchange surface and flexibility in tiny vessels'],['RBC & haemoglobin','6.1','RBC mitochondria','absent, so RBCs do not consume the oxygen they carry'],['RBC & haemoglobin','6.1','Main RBC function','transport oxygen and some carbon dioxide'],['RBC & haemoglobin','6.1','RBC production site','red bone marrow'],['RBC & haemoglobin','6.1','Approximate RBC lifespan','about 120 days'],['RBC & haemoglobin','6.1','Haematocrit / PCV','percentage of whole blood made up of red blood cells'],['RBC & haemoglobin','6.1','Haemoglobin','iron-containing intracellular protein inside RBCs that carries oxygen'],['RBC & haemoglobin','6.1','Percentage of blood oxygen carried by haemoglobin','about 97%'],['RBC & haemoglobin','6.1','Haemoglobin structure','4 globin chains and 4 haeme groups'],['RBC & haemoglobin','6.1','Oxygen-binding site in haemoglobin','iron ion in each haeme group'],['RBC & haemoglobin','6.1','Oxygen capacity of one haemoglobin molecule','4 oxygen molecules'],['RBC & haemoglobin','6.1','Essential raw material for haemoglobin','iron'],['RBC & haemoglobin','6.1','Female haemoglobin reference range in 6.1','115–155 g/L'],['RBC & haemoglobin','6.1','Male haemoglobin reference range in 6.1','130–175 g/L'],
['White cells & platelets','6.1','Leukocyte','the scientific name for a white blood cell'],['White cells & platelets','6.1','General leukocyte function','defence against infection and removal of pathogens/debris'],['White cells & platelets','6.1','Leukocyte appearance','larger than RBCs with a visible nucleus'],['White cells & platelets','6.1','Phagocytosis','engulfing and destroying pathogens or cellular debris'],['White cells & platelets','6.1','Differential white count','a test that counts the different WBC types individually'],['White cells & platelets','6.1','Neutrophil','the most common WBC; a phagocyte that rises in acute infection'],['White cells & platelets','6.1','Thrombocyte','the scientific name for a platelet'],['White cells & platelets','6.1','Platelet structure','tiny irregular cell fragment, not a complete cell'],['White cells & platelets','6.1','Platelet function','blood clotting and platelet-plug formation'],['White cells & platelets','6.1','Too few platelets','increased risk of excessive bleeding'],
['Blood cell production','6.1','Haematopoiesis','production of new blood cells'],['Blood cell production','6.1','Erythropoiesis','production of erythrocytes'],['Blood cell production','6.1','Leukopoiesis','production of leukocytes'],['Blood cell production','6.1','Thrombopoiesis','production of thrombocytes/platelets'],['Blood cell production','6.1','Erythropoietin (EPO)','kidney hormone that stimulates red bone marrow to make more RBCs'],['Blood cell production','6.1','Trigger for EPO release','low oxygen levels in the blood'],['Blood cell production','6.1','Response to infection or inflammation','increase leukocyte production'],['Blood cell production','6.1','Response to injury/bleeding','increase thrombocyte production'],['Blood cell production','6.1','Response to low oxygen','increase erythrocyte production'],
['Blood groups','6.1','Antigen','surface marker on an RBC recognised by the immune system'],['Blood groups','6.1','Antibody','plasma protein that recognises and binds a specific foreign antigen'],['Blood groups','6.1','Type A blood','A antigen on RBCs and anti-B antibody in plasma'],['Blood groups','6.1','Type B blood','B antigen on RBCs and anti-A antibody in plasma'],['Blood groups','6.1','Type AB blood','A and B antigens and no anti-A/anti-B antibodies'],['Blood groups','6.1','Type O blood','no A or B antigens and both anti-A and anti-B antibodies'],['Blood groups','6.1','Rh-positive','Rh/D antigen is present on RBCs'],['Blood groups','6.1','Rh-negative','Rh/D antigen is absent from RBCs'],['Blood groups','6.1','Agglutination','clumping of RBCs after antibodies bind incompatible antigens'],['Blood groups','6.1','ABO compatibility rule','recipient antibodies must not attack donor RBC antigens'],['Blood groups','6.1','Universal ABO red-cell donor','type O'],['Blood groups','6.1','Universal ABO red-cell recipient','type AB'],['Blood groups','6.1','Universal red-cell donor including Rh','O negative'],['Blood groups','6.1','Universal red-cell recipient including Rh','AB positive'],
['Haemostasis','6.1','Haemostasis','rapid localised process that stops bleeding after vessel injury'],['Haemostasis','6.1','Step 1 of haemostasis','vascular spasm'],['Haemostasis','6.1','Vascular spasm','vasoconstriction of the damaged vessel to reduce blood flow'],['Haemostasis','6.1','Step 2 of haemostasis','platelet plug formation'],['Haemostasis','6.1','Platelet plug formation','activated sticky platelets accumulate at the damaged site'],['Haemostasis','6.1','Step 3 of haemostasis','coagulation'],['Haemostasis','6.1','Coagulation','clotting process that produces a stable fibrin-reinforced clot'],['Haemostasis','6.1','Fibrin','netlike protein fibres that trap cells and strengthen the clot'],
['Lab & blood tests','6.2','Blood-smear erythrocyte clue','small biconcave disc with no nucleus'],['Lab & blood tests','6.2','Blood-smear leukocyte clue','larger cell with a dark nucleus; neutrophils have a multilobed nucleus'],['Lab & blood tests','6.2','Blood-smear thrombocyte clue','tiny cell fragments'],['Lab & blood tests','6.2','Adult female haematocrit reference range','36.9–44.6%'],['Lab & blood tests','6.2','Adult male haematocrit reference range','41.5–50.4%'],['Lab & blood tests','6.2','Haematocrit formula','RBC length or volume ÷ total blood length or volume × 100'],['Lab & blood tests','6.2','CBC','complete blood count; measures numbers and characteristics of formed elements'],['Lab & blood tests','6.2','MCV','mean corpuscular volume; average size of red blood cells'],['Lab & blood tests','6.2','HGB','haemoglobin measurement in the blood'],['Lab & blood tests','6.2','WBC differential','counts each white-blood-cell type separately'],['Lab & blood tests','6.2','Platelet count','number of platelets in the blood'],['Lab & blood tests','6.2','Blood protein reference range','60–80 g/L for >4 years to adult'],['Lab & blood tests','6.2','Fasting glucose reference range','3.0–5.4 mmol/L'],['Lab & blood tests','6.2','Bruise','blood enters surrounding tissue after small vessels break without breaking the overlying skin'],
['Revision','6.3','Plasma proportion in revision tube','about 55%'],['Revision','6.3','Buffy coat contents','white blood cells and platelets'],['Revision','6.3','Four oxygen molecules','maximum carried by one haemoglobin molecule'],['Revision','6.3','B+ blood antigens','B antigen and Rh/D antigen'],['Revision','6.3','Three haemostasis steps','vascular spasm → platelet plug → coagulation']
];
const group={};T.forEach(x=>(group[x[0]]??=[]).push(x));const defs=(row)=>{const pool=group[row[0]].filter(x=>x!==row).map(x=>x[3]);return [...new Set(pool)].slice(0,3)};const terms=(row)=>{const pool=group[row[0]].filter(x=>x!==row).map(x=>x[2]);return [...new Set(pool)].slice(0,3)};T.forEach((r,i)=>{const [topic,lesson,term,def]=r;let d1=defs(r);if(d1.length<3)d1=[...d1,...T.filter(x=>x!==r).map(x=>x[3]).filter(x=>!d1.includes(x))].slice(0,3);A(topic,`Which statement best describes ${term}?`,def,d1,`${term}: ${def}.`,`${lesson}${lesson==='6.2'?' lab':''}${lesson==='6.3'?' revision':''}`);let d2=terms(r);if(d2.length<3)d2=[...d2,...T.filter(x=>x!==r).map(x=>x[2]).filter(x=>!d2.includes(x))].slice(0,3);A(topic,`Which term matches this description: ${def}?`,term,d2,`The correct term is ${term}.`,`${lesson}${lesson==='6.2'?' lab':''}${lesson==='6.3'?' revision':''}`)});
const S=[
['Blood composition','6.0','A centrifuged tube has a pale-yellow top layer. What is it?','Plasma','Buffy coat|Red blood cells|Fibrin clot','Plasma forms the top, straw-coloured layer.','lab','tube'],
['Blood composition','6.0','Which centrifuged layer contains both WBCs and platelets?','Buffy coat','Plasma|RBC pellet|Serum only','The buffy coat lies between plasma and RBCs.','lab','tube'],
['RBC & haemoglobin','6.1','Why can an RBC squeeze through tiny capillaries efficiently?','Its biconcave shape makes it flexible','It has a large nucleus|It has a thick collagen wall|It is a platelet fragment','Biconcave RBCs are flexible and have a high surface-area-to-volume ratio.',''],
['RBC & haemoglobin','6.1','A woman has haemoglobin 100 g/L. Using the 6.1 course range, this is…','low / anaemic range','normal|high|a platelet result','The course female range is 115–155 g/L.','revision'],
['Blood cell production','6.1','A person moves to high altitude and blood oxygen falls. Which sequence is correct?','Kidneys release EPO → red marrow makes more RBCs','Liver releases insulin → platelets rise|Kidneys release fibrin → WBCs rise|Lungs release EPO → RBCs fall','Low O₂ stimulates kidney EPO, which stimulates erythropoiesis.','revision'],
['Blood groups','6.1','Why can incompatible transfusion be dangerous?','Antibodies can bind donor RBC antigens causing agglutination and haemolysis','Plasma instantly turns to bone|RBCs lose all haemoglobin|Platelets become neurons','Incompatibility can cause RBC clumping and breakdown.','revision','abo'],
['Blood groups','6.1','A type A recipient can receive ABO red cells from…','A or O','B or AB|AB only|B only','A recipients have anti-B antibodies, so A and O donor RBCs are compatible in the ABO system.','revision','abo'],
['Blood groups','6.1','A type B recipient can receive ABO red cells from…','B or O','A or AB|AB only|A only','B recipients have anti-A antibodies.','revision','abo'],
['Blood groups','6.1','A type O recipient can receive ABO red cells from…','O only','A or O|B or O|A, B, AB or O','Type O plasma contains both anti-A and anti-B antibodies.','revision','abo'],
['Blood groups','6.1','A type AB recipient can receive ABO red cells from…','A, B, AB or O','AB only|O only|A and B only','AB recipients have no anti-A or anti-B antibodies.','revision','abo'],
['Haemostasis','6.1','Immediately after a vessel is damaged, what should happen first?','Vascular spasm / vasoconstriction','Fibrin breakdown|RBC production|Vasodilation','Vascular spasm reduces blood flow before the plug and clot develop.','revision'],
['Haemostasis','6.1','What transforms a temporary platelet plug into a stronger stable clot?','Coagulation with fibrin formation','Haematocrit|Haemolysis|Erythropoiesis','Fibrin reinforces the platelet plug.','revision'],
['Lab & blood tests','6.2','A haematocrit has 22 mm RBCs in 50 mm total blood. What is the Hct?','44%','22%|50%|78%','22 ÷ 50 × 100 = 44%.','lab','tube'],
['Lab & blood tests','6.2','A fasting glucose result is 2.5 mmol/L. Compared with 3.0–5.4 mmol/L it is…','low','normal|high|a haemoglobin value','2.5 is below the course fasting reference interval.','lab'],
['Lab & blood tests','6.2','An infection may cause which CBC change?','Higher white blood cell count','Zero plasma|Lower platelet size always|No formed elements','WBC numbers often rise during infection.','lab'],
['Revision','6.3','Type AB blood has which ABO antibodies?','Neither anti-A nor anti-B','anti-A only|anti-B only|both anti-A and anti-B','AB has both self antigens and normally neither ABO antibody.','revision','abo'],
['Revision','6.3','Type O blood has which ABO antigens?','Neither A nor B','A only|B only|A and B','Type O RBCs have neither A nor B antigen.','revision','abo']
];S.forEach(x=>A(x[0],x[2],x[3],x[4].split('|'),x[5],`${x[1]} ${x[6]||''}`,x[7]||''));})();